eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
    expiration-refresh: ${JWT_REFRESH_EXPIRATION}

rabbitmq:
  exchange: ${RABBITMQ_EXCHANGE}
  queue:
    user-registered: ${RABBITMQ_QUEUE_USER_REGISTERED}
    startup-created: ${RABBITMQ_QUEUE_STARTUP_CREATED}
    startup-approved: ${RABBITMQ_QUEUE_STARTUP_APPROVED}
    investment-created: ${RABBITMQ_QUEUE_INVESTMENT_CREATED}
    investment-approved: ${RABBITMQ_QUEUE_INVESTMENT_APPROVED}
    team-invite-sent: ${RABBITMQ_QUEUE_TEAM_INVITE_SENT}
  routing-key:
    user-registered: ${RABBITMQ_ROUTING_KEY_USER_REGISTERED}
    startup-created: ${RABBITMQ_ROUTING_KEY_STARTUP_CREATED}
    startup-approved: ${RABBITMQ_ROUTING_KEY_STARTUP_APPROVED}
    investment-created: ${RABBITMQ_ROUTING_KEY_INVESTMENT_CREATED}
    investment-approved: ${RABBITMQ_ROUTING_KEY_INVESTMENT_APPROVED}
    team-invite-sent: ${RABBITMQ_ROUTING_KEY_TEAM_INVITE_SENT}
