eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:YOUR_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:YOUR_PASSWORD_HERE}

app:
  jwt:
    secret: ${JWT_SECRET:YOUR_SECRET_KEY_GOES_HERE}
    expiration: ${JWT_EXPIRATION:86400000}
    expiration-refresh: ${JWT_REFRESH_EXPIRATION:604800000}
