server:
  port: 8081

spring:
  datasource:
    url: ${DB_AUTH_URL:jdbc:postgresql://localhost:5432/founderlink_auth_db}

rabbitmq:
  exchange: ${RABBITMQ_EXCHANGE:founderlink.exchange}
  routing-key:
    user-registered: user.registered
