server:
  port: 8081
spring:
  datasource:
    url: ${DB_AUTH_URL}
rabbitmq:
  queue:
    user-registered: ${RABBITMQ_QUEUE_USER_REGISTERED}
  routing-key:
    user-registered: ${RABBITMQ_ROUTING_KEY_USER_REGISTERED}
