server:
  port: 8082

spring:
  datasource:
    url: ${DB_USER_URL:jdbc:postgresql://localhost:5432/founderlink_user_db}

rabbitmq:
  queue:
    user-registered: user.registered.queue

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
