server:
  port: 8082
spring:
  datasource:
    url: ${DB_USER_URL}
rabbitmq:
  queue:
    user-registered: ${RABBITMQ_QUEUE_USER_REGISTERED}
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
